import type { MacroSeries } from "../types";
import { getSource } from "./registry";

function series(
  spec: Omit<MacroSeries, "agency" | "copyrightClass"> & { sourceId: string },
): MacroSeries {
  const source = getSource(spec.sourceId);
  if (!source) {
    throw new Error(`Series ${spec.seriesId} references unknown source ${spec.sourceId}`);
  }
  return {
    ...spec,
    agency: source.name,
    copyrightClass: source.licenseClass === "us-government-work"
      ? "U.S. government work: citation required"
      : source.license,
  };
}

/**
 * Curated overlay (~30 series). Official agency IDs only.
 * Fixture observations are illustrative. Live BLS/BEA/EIA/Census/Fed/Treasury are not called.
 * FRED mnemonics are not stored and are not a source of truth.
 */
export const SERIES_CATALOG: MacroSeries[] = [
  series({
    seriesId: "bls-cpi-u-all",
    officialId: "CUUR0000SA0",
    sourceId: "bls",
    label: "CPI-U, all items",
    unit: "index 1982-84=100",
    frequency: "monthly",
    citation: "U.S. Bureau of Labor Statistics, Consumer Price Index for All Urban Consumers (CPI-U), CUUR0000SA0.",
    officialUrl: "https://www.bls.gov/cpi/",
    plausibleFor: ["Automobile manufacturing", "Application software", "Regional bank"],
    fixture: { latestDisplay: "322.4", numeric: 322.4, asOf: "2026-01", note: "Fixture observation. Not a live BLS print." },
  }),
  series({
    seriesId: "bls-cpi-u-core",
    officialId: "CUSR0000SA0L1E",
    sourceId: "bls",
    label: "CPI-U, all items less food and energy",
    unit: "index 1982-84=100",
    frequency: "monthly",
    citation: "U.S. Bureau of Labor Statistics, CPI-U all items less food and energy, CUSR0000SA0L1E.",
    officialUrl: "https://www.bls.gov/cpi/",
    plausibleFor: ["Application software", "Regional bank"],
    fixture: { latestDisplay: "328.1", numeric: 328.1, asOf: "2026-01", note: "Fixture observation. Not a live BLS print." },
  }),
  series({
    seriesId: "bls-nfp",
    officialId: "CES0000000001",
    sourceId: "bls",
    label: "All employees, total nonfarm",
    unit: "thousands of persons",
    frequency: "monthly",
    citation: "U.S. Bureau of Labor Statistics, Current Employment Statistics, CES0000000001.",
    officialUrl: "https://www.bls.gov/ces/",
    plausibleFor: ["Automobile manufacturing", "Application software", "Regional bank"],
    fixture: { latestDisplay: "159,200", numeric: 159200, asOf: "2026-01", note: "Fixture observation. Not a live BLS print." },
  }),
  series({
    seriesId: "bls-unrate",
    officialId: "LNS14000000",
    sourceId: "bls",
    label: "Unemployment rate",
    unit: "percent",
    frequency: "monthly",
    citation: "U.S. Bureau of Labor Statistics, Current Population Survey, LNS14000000.",
    officialUrl: "https://www.bls.gov/cps/",
    plausibleFor: ["Automobile manufacturing", "Regional bank"],
    fixture: { latestDisplay: "4.2%", numeric: 4.2, asOf: "2026-01", note: "Fixture observation. Not a live BLS print." },
  }),
  series({
    seriesId: "bls-ahe-private",
    officialId: "CES0500000003",
    sourceId: "bls",
    label: "Average hourly earnings, total private",
    unit: "USD per hour",
    frequency: "monthly",
    citation: "U.S. Bureau of Labor Statistics, Current Employment Statistics, CES0500000003.",
    officialUrl: "https://www.bls.gov/ces/",
    plausibleFor: ["Application software", "Regional bank"],
    fixture: { latestDisplay: "$36.40", numeric: 36.4, asOf: "2026-01", note: "Fixture observation. Not a live BLS print." },
  }),
  series({
    seriesId: "bls-ahe-mfg",
    officialId: "CES3000000003",
    sourceId: "bls",
    label: "Average hourly earnings, manufacturing",
    unit: "USD per hour",
    frequency: "monthly",
    citation: "U.S. Bureau of Labor Statistics, Current Employment Statistics, CES3000000003.",
    officialUrl: "https://www.bls.gov/ces/",
    plausibleFor: ["Automobile manufacturing"],
    fixture: { latestDisplay: "+3.1% YoY", numeric: 3.1, asOf: "2026-01", note: "Fixture observation. Live BLS ingest is not enabled." },
  }),
  series({
    seriesId: "bls-ppi-mfg",
    officialId: "PCUOMFG--OMFG--",
    sourceId: "bls",
    label: "PPI, manufacturing",
    unit: "index",
    frequency: "monthly",
    citation: "U.S. Bureau of Labor Statistics, Producer Price Index industry data, PCUOMFG--OMFG--.",
    officialUrl: "https://www.bls.gov/ppi/",
    plausibleFor: ["Automobile manufacturing"],
    fixture: { latestDisplay: "+1.4% YoY", numeric: 1.4, asOf: "2026-01", note: "Fixture observation. Not a live BLS print." },
  }),
  series({
    seriesId: "bls-emp-auto",
    officialId: "CES3361100001",
    sourceId: "bls",
    label: "All employees, automobile manufacturing",
    unit: "thousands of persons",
    frequency: "monthly",
    citation: "U.S. Bureau of Labor Statistics, Current Employment Statistics, CES3361100001.",
    officialUrl: "https://www.bls.gov/ces/",
    plausibleFor: ["Automobile manufacturing"],
    fixture: { latestDisplay: "278.0", numeric: 278, asOf: "2026-01", note: "Fixture observation. Not a live BLS print." },
  }),
  series({
    seriesId: "bea-rgdp-pch",
    officialId: "NIPA T10101 A191RL",
    sourceId: "bea",
    label: "Real GDP, percent change",
    unit: "percent, annual rate",
    frequency: "quarterly",
    citation: "U.S. Bureau of Economic Analysis, NIPA Table 1.1.1, line A191RL.",
    officialUrl: "https://www.bea.gov/data/gdp/gross-domestic-product",
    plausibleFor: ["Automobile manufacturing", "Application software", "Regional bank"],
    fixture: { latestDisplay: "+2.1%", numeric: 2.1, asOf: "2025-Q4", note: "Fixture observation. Not a live BEA print." },
  }),
  series({
    seriesId: "bea-rpce",
    officialId: "NIPA T20405 DPCERX",
    sourceId: "bea",
    label: "Real personal consumption expenditures",
    unit: "index / chained dollars",
    frequency: "quarterly",
    citation: "U.S. Bureau of Economic Analysis, NIPA Table 2.4.5, DPCERX.",
    officialUrl: "https://www.bea.gov/data/consumer-spending/main",
    plausibleFor: ["Automobile manufacturing", "Application software"],
    fixture: { latestDisplay: "+2.4% YoY", numeric: 2.4, asOf: "2025-Q4", note: "Fixture observation. Not a live BEA print." },
  }),
  series({
    seriesId: "bea-gpdi",
    officialId: "NIPA T10105 A006RC",
    sourceId: "bea",
    label: "Gross private domestic investment",
    unit: "USD, current",
    frequency: "quarterly",
    citation: "U.S. Bureau of Economic Analysis, NIPA Table 1.1.5, A006RC.",
    officialUrl: "https://www.bea.gov/data/gdp/gross-domestic-product",
    plausibleFor: ["Automobile manufacturing", "Application software"],
    fixture: { latestDisplay: "+3.0% YoY", numeric: 3.0, asOf: "2025-Q4", note: "Fixture observation. Not a live BEA print." },
  }),
  series({
    seriesId: "bea-pfi-software",
    officialId: "NIPA T50305 Y033RC",
    sourceId: "bea",
    label: "Private fixed investment, software",
    unit: "USD, current",
    frequency: "quarterly",
    citation: "U.S. Bureau of Economic Analysis, NIPA Table 5.3.5, software (Y033RC).",
    officialUrl: "https://www.bea.gov/data/investment-fixed-assets",
    plausibleFor: ["Application software"],
    fixture: { latestDisplay: "+6.8% YoY", numeric: 6.8, asOf: "2025-Q4", note: "Fixture overlay. Not a company forecast. Live BEA ingest is not enabled." },
  }),
  series({
    seriesId: "bea-va-auto",
    officialId: "GDP-by-Industry Motor vehicles, bodies and trailers, and parts",
    sourceId: "bea",
    label: "Value added, motor vehicles and parts",
    unit: "USD, current",
    frequency: "quarterly",
    citation: "U.S. Bureau of Economic Analysis, GDP by Industry, motor vehicles, bodies and trailers, and parts.",
    officialUrl: "https://www.bea.gov/data/gdp/gdp-industry",
    plausibleFor: ["Automobile manufacturing"],
    fixture: { latestDisplay: "+1.8% YoY", numeric: 1.8, asOf: "2025-Q4", note: "Fixture observation. Not a live BEA print." },
  }),
  series({
    seriesId: "bea-psr",
    officialId: "NIPA T20100 A072RC",
    sourceId: "bea",
    label: "Personal saving rate",
    unit: "percent",
    frequency: "quarterly",
    citation: "U.S. Bureau of Economic Analysis, NIPA Table 2.1, A072RC.",
    officialUrl: "https://www.bea.gov/data/income-saving/personal-saving-rate",
    plausibleFor: ["Automobile manufacturing", "Regional bank"],
    fixture: { latestDisplay: "4.6%", numeric: 4.6, asOf: "2025-Q4", note: "Fixture observation. Not a live BEA print." },
  }),
  series({
    seriesId: "eia-wti",
    officialId: "PET.RWTC.D",
    sourceId: "eia",
    label: "Cushing OK WTI spot price",
    unit: "USD per barrel",
    frequency: "daily",
    citation: "U.S. Energy Information Administration, Petroleum & Other Liquids, PET.RWTC.D.",
    officialUrl: "https://www.eia.gov/dnav/pet/pet_pri_spt_s1_d.htm",
    plausibleFor: ["Automobile manufacturing"],
    fixture: { latestDisplay: "$74.20", numeric: 74.2, asOf: "2026-02-18", note: "Fixture observation. Not a live EIA print." },
  }),
  series({
    seriesId: "eia-hhub",
    officialId: "NG.RNGWHHD.D",
    sourceId: "eia",
    label: "Henry Hub natural gas spot price",
    unit: "USD per MMBtu",
    frequency: "daily",
    citation: "U.S. Energy Information Administration, Natural Gas, NG.RNGWHHD.D.",
    officialUrl: "https://www.eia.gov/dnav/ng/ng_pri_fut_s1_d.htm",
    plausibleFor: ["Automobile manufacturing"],
    fixture: { latestDisplay: "$3.15", numeric: 3.15, asOf: "2026-02-18", note: "Fixture observation. Not a live EIA print." },
  }),
  series({
    seriesId: "eia-crude-prod",
    officialId: "PET.MCRFPUS2.M",
    sourceId: "eia",
    label: "U.S. field production of crude oil",
    unit: "thousand barrels per day",
    frequency: "monthly",
    citation: "U.S. Energy Information Administration, PET.MCRFPUS2.M.",
    officialUrl: "https://www.eia.gov/dnav/pet/pet_crd_crpdn_adc_mbblpd_m.htm",
    plausibleFor: ["Automobile manufacturing"],
    fixture: { latestDisplay: "13,420", numeric: 13420, asOf: "2026-01", note: "Fixture observation. Not a live EIA print." },
  }),
  series({
    seriesId: "eia-netgen",
    officialId: "ELEC.GEN.ALL-US-99.M",
    sourceId: "eia",
    label: "Net generation, all fuels, U.S.",
    unit: "thousand MWh",
    frequency: "monthly",
    citation: "U.S. Energy Information Administration, Electricity, ELEC.GEN.ALL-US-99.M.",
    officialUrl: "https://www.eia.gov/electricity/data.php",
    plausibleFor: ["Application software"],
    fixture: { latestDisplay: "352,000", numeric: 352000, asOf: "2026-01", note: "Fixture observation. Not a live EIA print." },
  }),
  series({
    seriesId: "eia-pet-imports",
    officialId: "PET.MTTIMUS1.M",
    sourceId: "eia",
    label: "U.S. imports of crude oil and petroleum products",
    unit: "thousand barrels",
    frequency: "monthly",
    citation: "U.S. Energy Information Administration, PET.MTTIMUS1.M.",
    officialUrl: "https://www.eia.gov/dnav/pet/pet_move_imp_dc_NUS-Z00_mbbl_m.htm",
    plausibleFor: ["Automobile manufacturing"],
    fixture: { latestDisplay: "246,000", numeric: 246000, asOf: "2026-01", note: "Fixture observation. Not a live EIA print." },
  }),
  series({
    seriesId: "census-marts-auto",
    officialId: "MARTS / MRTS NAICS 441",
    sourceId: "census",
    label: "Advance retail sales, motor vehicle and parts dealers",
    unit: "USD millions",
    frequency: "monthly",
    citation: "U.S. Census Bureau, Advance Monthly Retail Trade Survey, NAICS 441.",
    officialUrl: "https://www.census.gov/retail/index.html",
    plausibleFor: ["Automobile manufacturing"],
    fixture: { latestDisplay: "+2.2% YoY", numeric: 2.2, asOf: "2026-01", note: "Fixture observation. Not a live Census print." },
  }),
  series({
    seriesId: "census-m3-durable",
    officialId: "M3 Manufacturers' New Orders, Durable Goods",
    sourceId: "census",
    label: "Manufacturers' new orders, durable goods",
    unit: "USD millions",
    frequency: "monthly",
    citation: "U.S. Census Bureau, Manufacturers' Shipments, Inventories, and Orders (M3).",
    officialUrl: "https://www.census.gov/manufacturing/m3/",
    plausibleFor: ["Automobile manufacturing"],
    fixture: { latestDisplay: "+0.8% MoM", numeric: 0.8, asOf: "2026-01", note: "Fixture observation. Not a live Census print." },
  }),
  series({
    seriesId: "census-housing-starts",
    officialId: "New Residential Construction, total housing starts",
    sourceId: "census",
    label: "Housing starts, total",
    unit: "thousands of units, annual rate",
    frequency: "monthly",
    citation: "U.S. Census Bureau, New Residential Construction.",
    officialUrl: "https://www.census.gov/construction/nrc/",
    plausibleFor: ["Regional bank"],
    fixture: { latestDisplay: "1,360", numeric: 1360, asOf: "2026-01", note: "Fixture observation. Not a live Census print." },
  }),
  series({
    seriesId: "census-bfs-highprop",
    officialId: "BFS high-propensity business applications",
    sourceId: "census",
    label: "High-propensity business applications",
    unit: "count",
    frequency: "weekly",
    citation: "U.S. Census Bureau, Business Formation Statistics.",
    officialUrl: "https://www.census.gov/econ/bfs/index.html",
    plausibleFor: ["Application software", "Regional bank"],
    fixture: { latestDisplay: "18,400", numeric: 18400, asOf: "2026-W06", note: "Fixture observation. Not a live Census print." },
  }),
  series({
    seriesId: "census-qss-info",
    officialId: "QSS Information, NAICS 51",
    sourceId: "census",
    label: "Quarterly services, information sector",
    unit: "USD millions",
    frequency: "quarterly",
    citation: "U.S. Census Bureau, Quarterly Services Survey, NAICS 51 Information.",
    officialUrl: "https://www.census.gov/services/index.html",
    plausibleFor: ["Application software"],
    fixture: { latestDisplay: "+5.1% YoY", numeric: 5.1, asOf: "2025-Q4", note: "Fixture observation. Not a live Census print." },
  }),
  series({
    seriesId: "fed-ffr",
    officialId: "H.15 Federal funds effective rate",
    sourceId: "fed",
    label: "Federal funds effective rate",
    unit: "percent",
    frequency: "daily",
    citation: "Board of Governors of the Federal Reserve System, Statistical Release H.15, federal funds (effective).",
    officialUrl: "https://www.federalreserve.gov/releases/h15/",
    plausibleFor: ["Regional bank", "Automobile manufacturing"],
    fixture: { latestDisplay: "4.33%", numeric: 4.33, asOf: "2026-02-20", note: "Fixture observation. From H.15, not a FRED alias." },
  }),
  series({
    seriesId: "fed-prime",
    officialId: "H.15 Bank prime loan rate",
    sourceId: "fed",
    label: "Bank prime loan rate",
    unit: "percent",
    frequency: "daily",
    citation: "Board of Governors of the Federal Reserve System, Statistical Release H.15, bank prime loan rate.",
    officialUrl: "https://www.federalreserve.gov/releases/h15/",
    plausibleFor: ["Regional bank"],
    fixture: { latestDisplay: "7.50%", numeric: 7.5, asOf: "2026-02-20", note: "Fixture observation. From H.15, not a FRED alias." },
  }),
  series({
    seriesId: "nyfed-sofr",
    officialId: "SOFR",
    sourceId: "nyfed",
    label: "Secured Overnight Financing Rate",
    unit: "percent",
    frequency: "daily",
    citation: "Federal Reserve Bank of New York, Secured Overnight Financing Rate (SOFR).",
    officialUrl: "https://www.newyorkfed.org/markets/reference-rates/sofr",
    plausibleFor: ["Regional bank"],
    fixture: { latestDisplay: "4.31%", numeric: 4.31, asOf: "2026-02-20", note: "Fixture observation. From NY Fed, not a FRED alias." },
  }),
  series({
    seriesId: "nyfed-auto-rate",
    officialId: "Household Debt and Credit / CCP auto loan interest rate",
    sourceId: "nyfed",
    label: "Auto loan interest rate",
    unit: "percent",
    frequency: "quarterly",
    citation: "Federal Reserve Bank of New York, Center for Microeconomic Data, Household Debt and Credit (auto loans).",
    officialUrl: "https://www.newyorkfed.org/microeconomics/hhdc",
    plausibleFor: ["Automobile manufacturing", "Regional bank"],
    fixture: { latestDisplay: "7.4%", numeric: 7.4, asOf: "2026-01", note: "Economically plausible driver — not a causal claim. Fixture series." },
  }),
  series({
    seriesId: "nyfed-auto-dq",
    officialId: "Household Debt and Credit auto loan 90+ day delinquency",
    sourceId: "nyfed",
    label: "Auto loan 90+ day delinquency rate",
    unit: "percent",
    frequency: "quarterly",
    citation: "Federal Reserve Bank of New York, Quarterly Report on Household Debt and Credit, auto loans.",
    officialUrl: "https://www.newyorkfed.org/microeconomics/hhdc",
    plausibleFor: ["Automobile manufacturing", "Regional bank"],
    fixture: { latestDisplay: "3.1%", numeric: 3.1, asOf: "2025-Q4", note: "Fixture observation. Not a live NY Fed print." },
  }),
  series({
    seriesId: "treas-yc-2y",
    officialId: "Daily Treasury Par Yield Curve Rate, 2 Year",
    sourceId: "treasury",
    label: "Treasury par yield, 2 year",
    unit: "percent",
    frequency: "daily",
    citation: "U.S. Department of the Treasury, Daily Treasury Par Yield Curve Rates, 2 Year.",
    officialUrl: "https://home.treasury.gov/resource-center/data-chart-center/interest-rates",
    plausibleFor: ["Regional bank"],
    fixture: { latestDisplay: "3.79%", numeric: 3.79, asOf: "2026-02-20", note: "Fixture observation. Treasury original, not FRED." },
  }),
  series({
    seriesId: "treas-yc-10y",
    officialId: "Daily Treasury Par Yield Curve Rate, 10 Year",
    sourceId: "treasury",
    label: "Treasury par yield, 10 year",
    unit: "percent",
    frequency: "daily",
    citation: "U.S. Department of the Treasury, Daily Treasury Par Yield Curve Rates, 10 Year.",
    officialUrl: "https://home.treasury.gov/resource-center/data-chart-center/interest-rates",
    plausibleFor: ["Regional bank", "Automobile manufacturing"],
    fixture: { latestDisplay: "4.21%", numeric: 4.21, asOf: "2026-02-20", note: "Fixture observation. Treasury original, not FRED." },
  }),
  series({
    seriesId: "treas-debt-penny",
    officialId: "Debt to the Penny, Tot_Public_Debt_Outstanding",
    sourceId: "treasury",
    label: "Total public debt outstanding",
    unit: "USD",
    frequency: "daily",
    citation: "U.S. Department of the Treasury, Fiscal Data, Debt to the Penny.",
    officialUrl: "https://fiscaldata.treasury.gov/datasets/debt-to-the-penny/debt-to-the-penny",
    plausibleFor: ["Regional bank"],
    fixture: { latestDisplay: "$36.4T", numeric: 36.4e12, asOf: "2026-02-20", note: "Fixture observation. Not a live Fiscal Data print." },
  }),
  series({
    seriesId: "treas-dts-cash",
    officialId: "DTS Operating Cash Balance",
    sourceId: "treasury",
    label: "Treasury operating cash balance",
    unit: "USD millions",
    frequency: "daily",
    citation: "U.S. Department of the Treasury, Fiscal Data, Daily Treasury Statement, operating cash balance.",
    officialUrl: "https://fiscaldata.treasury.gov/datasets/daily-treasury-statement/",
    plausibleFor: ["Regional bank"],
    fixture: { latestDisplay: "$812B", numeric: 812e9, asOf: "2026-02-20", note: "Fixture observation. Not a live DTS print." },
  }),
  series({
    seriesId: "treas-mts-receipts",
    officialId: "MTS Total Receipts",
    sourceId: "treasury",
    label: "Monthly Treasury receipts, total",
    unit: "USD millions",
    frequency: "monthly",
    citation: "U.S. Department of the Treasury, Fiscal Data, Monthly Treasury Statement, total receipts.",
    officialUrl: "https://fiscaldata.treasury.gov/datasets/monthly-treasury-statement/",
    plausibleFor: ["Regional bank"],
    fixture: { latestDisplay: "$412B", numeric: 412e9, asOf: "2026-01", note: "Fixture observation. Not a live MTS print." },
  }),
];

export function listSeries(): MacroSeries[] {
  return SERIES_CATALOG;
}

export function getSeries(seriesId: string): MacroSeries | undefined {
  return SERIES_CATALOG.find((s) => s.seriesId === seriesId);
}

export function seriesForIndustry(industry: string): MacroSeries[] {
  return SERIES_CATALOG.filter((s) => s.plausibleFor.includes(industry));
}
